const {countrylist,getselectedstate,getSearch,statelist,loginuser,signupuser,signupuserweb,getallusers,savepunchin,savepunchout,userupdatestatus,userdeletesuper,activationverification,planupgrades,getDetail,addsubscriptions,billingdetail,billingcompany,getsubscription,getsubscriptiondetail,editprofile,usereditservice,updatepayment,datatransfer,productivityinfo } = require('../controllers/user.controller');
const { checkToken } = require("../middleware/authjwt.js");
const express = require('express');
const router = express.Router();

//router.post('/', createUser);
router.get('/countrylist', countrylist);
router.post("/getstate",  getselectedstate);
router.post("/updatepayment",  updatepayment);
router.post("/getSearch",  getSearch);
router.post("/getDetail",  getDetail);
router.post("/getsubscription",  getsubscription);
router.post("/getsubscriptiondetail",checkToken,  getsubscriptiondetail);
router.get('/statelist', statelist);
router.post('/login', loginuser);
router.post('/signup', signupuser);
router.post('/signupweb', signupuserweb);
router.post("/userlist", checkToken, getallusers);
router.post('/billingdetail',checkToken, billingdetail);
router.post('/billingcompany',checkToken, billingcompany);
router.post("/userupdatestatus", checkToken, userupdatestatus);
router.post('/userdeletesuper',checkToken, userdeletesuper);
router.post("/punchin", checkToken, savepunchin);
router.post("/punchout", checkToken, savepunchout);
router.post("/activationverification",  activationverification);
router.post("/planupgrades",checkToken,  planupgrades);
router.post("/addsubscriptions",checkToken,  addsubscriptions);
router.post("/usereditservice",checkToken,  usereditservice);
router.post("/editprofile",checkToken,  editprofile);
router.post("/datatransfer",checkToken,  datatransfer);
router.get("/productivityinfo",checkToken,  productivityinfo);
/*router.post('/createcalllog/:id', createcalllog);
router.post('/createsmslog/:id', createsmslog);
router.post('/createlocation/:id', createlocation);
router.post('/createapplist/:id', createapplist);
router.post('/uploadphotodetail/:id', uploadphotodetail);
router.post('/loginuserweb', loginuserweb);
router.post('/calllogweb', calllogweb);
router.post('/smslogweb', smslogweb);
router.post('/applistweb', applistweb);
router.post('/locationweb', locationweb);
router.post('/locationweblist', locationweblist);
router.post('/captureweb', captureweb);
router.post('/recordweb', recordweb);
router.post('/deletelocation', deletelocation);
router.post('/userdeletesuper', userdeletesuper);
router.post('/deletecalllog', deletecalllog);
router.post('/deletesmslog', deletesmslog);
router.post('/deleteapplist', deleteapplist);
router.post('/deletecapturelist', deletecapturelist);
router.post('/deleterecord', deleterecord);
router.post('/userlist', userlist);
router.post('/userupdatestatus', userupdatestatus);
router.post('/testimonial', testimonial);
router.post('/testimonialstatus', testimonialstatus);
router.post('/testimonialdelete', testimonialdelete);
router.post('/testimonialedit', testimonialedit); 
router.post('/testimonialedituserservice', testimonialedituserservice); 
router.post('/testimonialaddservice', testimonialaddservice); 
router.post('/signupweb', signupweb);  */
//router.get('/', getalluser);
//router.get('/:id', getuserbyID);
//router.patch('/', updateuserbyID);
// router.delete('/', deleteuserbyID);
module.exports = router;